### PR TITLE
Decryption

### PR DESCRIPTION
**Pull request by rfornea**
This adds encryption and decryption methods that match what's being used on the brokernode, and switches to sha3_256 for the sidechain.  

This PR does not attempt to integrate the new encryption.  I would rather we handle that in a separate PR.  

To use the decryption method, it needs the following params in this order:
**key**:  the sha3_256 hash in the sidechain
**secret**:  the message or signatureMessageFragment.  Can only use first 96 characters so do .substring(0, 96)
**nonce**:  the sha256 hash that the sidechain is derived from.  This must be the sha256 hash, not the sha384 hash or the value in trytes.

### CODE REVIEW

**Comment by rfornea** [comment]
Whichever of us ends up implementing this, once we verify that it works and we can unlock treasure, just replace the existing encrypt/decrypt methods with what's in forgeEncrypt/forgeDecrypt.  

Also, do we need that setup-tests.js file?  I can pull that out if we don't.

**Comment by AaronVasquez** [comment]
I don't think we need setup-tests.js. It was probably a generated file.

**Comment by sonwani237** [comment]
Hello  Sirawesomeknight ,
I an getting encrypted data from api how to decrypt it.
Encrypted Data-
p1SvSCiAxupKrrZXzjXQk48EeA7F1jnGymvqGlmAOMOrnUVZpopohJ8WYp/DI3nUuc4wG57FQWi2
TfwS+H7VSsanfbhKGf+i6H1iQchaSi9lgjxv96JCyhM9WaF7T9UuL5efwgwslGqGG54Ctx6Ykg==

It's decryption-
{
  "status": {
    "status": "500",
    "message": "Your request could not be served by the system. Please try again!"
  }
}

Thanks in advance Please solve it

**Comment by rfornea** [comment]
@sonwani237   Are you sure you are commenting on the right project?

**Pull request merged**
